### ISSUE TITLE
Player community interaction incentive

### ISSUE THREAD

**Issue by Sriram-7451** [Sriram-7451/ZeldaFeatExension#4]
Player incentive to interact with NPC needs to be built around the quest.

- [x] Interaction and doing NPC quests should give unique materials and blueprints

- [x] Completion of those question should give them that as reward

- [x] Tips and guide hidden in conversation with NPCs for material obtaining and Building structures

- [ ] Test for API integration, design and gameplay

**Comment by Sriram-7451** [comment]
Code review @jayakumar0812

**Comment by jayakumar0812** [comment]
Reviewed good to go.

**Comment by Sriram-7451** [comment]
Moved to testing @JohnKirubaharan
